Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 10
    Tracing: Active

Resources:

  ListPostsFunction:
    Type: 'AWS::Serverless::Function'
    
    Properties:
      CodeUri: ./dist
      Handler: main.listPostsHandler
      
      Events:
        ListPostsApi:
            Type: Api
            Properties:
                Path: /posts
                Method: GET
  
  CreatePostFunction:
    Type: 'AWS::Serverless::Function'
    
    Properties:
      CodeUri: ./dist
      Handler: main.createPostHandler
      
      Events:
        ListPostsApi:
            Type: Api
            Properties:
                Path: /posts
                Method: POST
